
server_ip = "192.168.56.110"

agent_ip = "192.168.56.111"

Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/bionic64"

  # Server machine configuration
  config.vm.define "mbaniS" do |control|
    control.vm.hostname = "mbaniS"
    control.vm.network "private_network", ip: server_ip
    control.vm.network "forwarded_port", guest: 6443, host: 6443
      control.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", "mbaniS"]
        v.memory = '1024'
        v.cpus = 1
      end 
    control.vm.provision "shell", path: "scripts/k3s_server.sh", args: [server_ip]
  end

  # Agent machine configuration
  config.vm.define "mbaniSW" do |control|
    control.vm.hostname = "mbaniSW"
    control.vm.network "private_network", ip: agent_ip
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "mbaniSW"]
      v.memory = '521'
      v.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/k3s_worker.sh", args: [server_ip]
  end

end
