apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  selector:
    matchLabels:
      run: app1
  template:
    metadata:
      labels:
        run: app1
    spec:
      containers:
        - name: app1
          image: paulbouwer/hello-kubernetes:1
          ports:
            - containerPort: 80
              protocol: TCP
          env:
          - name: MESSAGE
            value: "Hello from app1"
          - name: PORT
            value: "80"

---

apiVersion: v1
kind: Service
metadata:
  name: app-one
  labels:
    run: app1
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: app1

